language: java
jdk:
 - oraclejdk8
sudo: false
install: true
script: ./scripts/build-lider-console.sh
notifications:
  email:
    recipients:
      - emre.akkaya@agem.com.tr
      - cemre.alpsoy@agem.com.tr
      - volkan.sahin@agem.com.tr
      - caner.feyzullahoglu@agem.com.tr
